config/routes.rb
Ticketee::Application.routes.draw do
  root "projects#index"
  
  resources :projects do
    resources :tickets do
      get :search, on: :collection
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      delete :remove, on: :member
    end
  end

  namespace :admin do
    root "base#index"
    resources :states do
      get :make_default, on: :member
    end
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end
  
  resources :users
  resources :files
  
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, polymorphic: true
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_action :find_user
  
  def index
    @ability = Ability.new(@user)
    @projects = Project.all
  end
  
  def set
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      project = Project.find id
      permissions.each do |action, checked|
        Permission.create!( user: @user, thing: project, action: action)
      end
    end
    flash[:notice] = "Permissions updated"
    redirect_to [:admin, @user, :permissions]
  end
  
  private
  
  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
  def permissions
    {
      "view" => "View",
      "create tickets" => "Create Tickets",
      "edit tickets" => "Edit Tickets",
      "delete tickets" => "Delete Tickets",
      "change states" => "Change States"
    }
  end
end

app/views/admin/permissions/index.html.erb
<h2>Permissions for <%= @user.email %></h2>
<%= form_tag admin_user_set_permissions_path, method: :put do %>
  <table id="permissions" cellspacing="0">
    <thead>
      <th>Project</th>
      <% permissions.each do |name, text| %>
        <th><%= text %></th>
      <% end %>
    </thead>
    
    <tbody>
      <% @projects.each do |project| %>
        <tr id="<%=dom_id(project)%>">
          <td><%= project.name %></td>
          <% permissions.each do |name, text| %>
            <td>
              <%= check_box_tag "permissions[#{project.id}][#{name}]", 
                  1, 
                  @ability.can?(name.to_sym, project) %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= submit_tag "Update" %>
<% end %>