config/routes.rb
Ticketee::Application.routes.draw do
  root "projects#index"
  
  resources :projects do
    resources :tickets do
      get :search, on: :collection
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      delete :remove, on: :member
    end
  end

  namespace :admin do
    root "base#index"
    resources :states do
      get :make_default, on: :member
    end
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end
  
  resources :users
  resources :files
  
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :permissions, as: :thing
  
  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: {action: "view", user: user})
  end
  
  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:show, :index]
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.for(current_user)
  end
  
  def show
    @tickets = @project.tickets
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    
    if @project.save
      flash[:notice] = "Project has been created"
      redirect_to @project
    else
      flash[:alert] = "Project has not been created"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    
    if @project.update(project_params)
      flash[:notice] = "Project has been updated"
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated"
      render 'new'
    end
  end
  
  def destroy
    @project.destroy
    flash[:notice] = "Project has been destroyed"
    redirect_to projects_path
  end
  
  private
  
  def find_project
    @project = Project.for(current_user).find params[:id]
    
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found"
    redirect_to projects_path
  end
  
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div class="error_explanation">
    <%=pluralize @project.errors.count, "error" %> prohibiting this project from being created:
  </div>

  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h2>New Project</h2>
<%= form_for(@project) do |f| %>   
  <p>    
    <%= f.label :name %><br />    
    <%= f.text_field :name %>  
  </p>
  <p>    
    <%= f.label :description %><br />    
    <%= f.text_field :description %>  
  </p>
  <%= f.submit %> 
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% admin_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
  <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<% title("Projects", @project.name) %>
<h1><%= @project.name %></h1>

<% admin_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", @project, method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<% authorized? "create tickets", @project do %>
  <%= link_to "Create Ticket", [:new, @project, :ticket] %>
<% end %>
<%= form_tag search_project_tickets_path(@project), method: :get do %>
  <%= label_tag "search" %>
  <%= text_field_tag "search", params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
<ul id="tickets">
  <% @tickets.each do |ticket| %>
    <li>
      <%= render ticket.state if ticket.state %>
      <%= ticket.id %>  - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>