config/routes.rb
Ticketee::Application.routes.draw do
  root "projects#index"
  
  resources :projects do
    resources :tickets do
      get :search, on: :collection
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      delete :remove, on: :member
    end
  end

  namespace :admin do
    root "base#index"
    resources :states do
      get :make_default, on: :member
    end
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end
  
  resources :users
  resources :files
  
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_ticket
  
  def remove
    if can?(:tag, @ticket.project) || current_user.admin?
      @tag = @ticket.tags.find params[:id]
      @ticket.tags -= [@tag]
      @ticket.save
    else
      render nothing: true
    end
  end
  
  private
  
  def find_ticket
    @ticket = Ticket.find params[:ticket_id]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<p>
  <%= f.label :tag_names, "Tags" %>
  <%= f.text_field :tag_names %>
</p>

app/views/tags/_tag.html.erb
<span class="tag">
  <% authorized? :tag, @ticket.project do %>
  <%= link_to "X", remove_ticket_tag_path(@ticket, tag), method: :delete, remote: true, id: "delete-#{tag.name.parameterize}" %>
  <% end %>
  <%= link_to tag.name, search_project_tickets_path(@ticket.project, search: "tag:#{tag.name}") %>
</span>

app/views/tags/remove.js.erb
$('#delete-<%=@tag.name.parameterize%>').parent().remove();