config/routes.rb
Ticketee::Application.routes.draw do
  root "projects#index"
  
  resources :projects do
    resources :tickets do
      get :search, on: :collection
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      delete :remove, on: :member
    end
  end

  namespace :admin do
    root "base#index"
    resources :states do
      get :make_default, on: :member
    end
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end
  
  resources :users
  resources :files
  
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  

end

app/models/state.rb
class State < ActiveRecord::Base
  
  def to_s
    name
  end
  
  def default!
    State.find_by(default: true).try(:update!, default: false)
    
    update! default: true
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  
  def index
    @states = State.all
  end
  
  def new
    @state = State.new
  end
  
  def create
    @state = State.new(state_params)
    
    if @state.save
      flash[:notice] = "State has been created"
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created"
      render 'new'
    end
  end
  
  def make_default
    @state = State.find(params[:id])
    @state.default!
    flash[:notice] = "#{@state.name} is now the default state"
    redirect_to admin_states_path
  end
  
  private
  
  def state_params
    params.require(:state).permit(:name, :background, :color)
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>

  <% if @state.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@state.errors.count, "Error") %>prohibiting this State from being saved:</p>
      <ul>
        <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", [:new, :admin, :state] %>

<ul id="states">
  <% @states.each do |state| %>
    <li id="<%=dom_id(state)%>">
      <%= state.name %>
      <%= link_to "Make Default", make_default_admin_state_path(state) %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render "form" %>